### ISSUE TITLE
I couldn't detect any installed dependencies.

### ISSUE THREAD

**Issue by thevenomsnake** [ciromattia/kcc#660] opened 2024-01-07 12:07 UTC
**Describe the bug**

**Expected behavior**
I have already installed zip and KindleGen, but it still prompts me to install dependencies and the conversion function cannot run.

**Screenshots**
![20240107200534](https://github.com/ciromattia/kcc/assets/31892635/a8ca6d9f-f3ac-4eb6-95e4-3109bcba5374)

**Desktop (please complete the following information):**
 - OS: [Windows 11]

**Comment by thevenomsnake** [comment] 2024-01-07 12:08
5.6.5 btw

**Comment by thevenomsnake** [comment] 2024-01-07 12:13
I just put "kindlegen.exe" on the same floder and fixed it.Now still showing "Install 7z(link)"

**Comment by axu2** [comment] 2024-01-07 15:10
Why is the font different than usual? @thevenomsnake 

What happens when you type in these addresses into File Explorer? This is where KCC is looking for kindlegen and 7z

```
%LOCALAPPDATA%\Amazon\Kindle Previewer 3\lib\fc\bin\
C:\Program Files\7-Zip
```

**Comment by thevenomsnake** [comment] 2024-01-08 15:21
I understand now where the problem was. I usually avoid installing software on the C drive, so there were no files in the two default locations you mentioned. I reinstalled the software to the default location, and now the problem is resolved.

**Comment by shihong5858** [comment] 2024-03-12 15:12
I just found this issue and I think this should be fixed ...
I think kcc could try to locate the 7zip using system PATH, otherwise it's really confusing for people (this is not documented as well)

**Comment by axu2** [comment] 2024-03-12 15:19
@shihong5858 what version of kcc are you using? And where did you put the kcc.exe? It should search for kcc automatically if you didn't change default install path. 

Did windows 11 change something? Are you using win11?

**Comment by shihong5858** [comment] 2024-03-12 16:15
I'm running kcc 5.6.5 on Windows 10. kcc is located on E: drive while 7-zip is on D: drive. I tried uninstalled 7-zip and re-installed it on C: drive and the warning is gone and kcc function right.

I'm working on kcc-c2e now and was afraid the same issue could happen (I didn't verify it though since it's already on C: now) so I had to point it out. I think if we decide not to fix the mandatory path issue, atleast we should warn people in the README.

Thanks :)

**Comment by shihong5858** [comment] 2024-03-12 16:18
Just to point it out: when I work with kcc-c2e, the stupid behavior on Powershell environment variable drove me crazy as well. I'm not sure if c2e would have the same concern (the [Environment]::GetEnvironmentVariables vs $env:Path)

**Comment by axu2** [comment] 2024-03-12 16:20
@shihong5858 I think taking arbitrary drive letters would be a good feature. Is the only difference in the url C vs D?

**Comment by shihong5858** [comment] 2024-03-13 17:57
@axu2 right, I first installed 7z on D drive as lots ppl like me like to avoid installing software on default C drive.
 And now I uninstalled the D one and re-installed 7z on C, and kcc works fine now.

My suggestion would be reading the 7z from the environment (usually through PATH), which is how most Windows users config their machine when they face the missing dependency errors.

**Comment by axu2** [comment] 2024-03-13 18:12
I'll add the d and e drive as a search location for 7z. We do search path but 7z isn't added to path on install. You can tell because tying 7z into cmd doesn't work.

**Comment by shihong5858** [comment] 2024-03-13 18:16
> We do search path
I think in my case it wasn't searching the path, at least I saw the warning on UI and c2e error in Powershell when I have 7z added into PATH manually. I even tried 7z.exe in cmd and it's working (so I can confirm it was added into PATH)

**Closed** 2024-03-25 01:40 UTC
