### ISSUE TITLE
Linux 64 bit kcc 5.5.1

### ISSUE THREAD

**Issue by aleifuu** [ciromattia/kcc#322] opened 2019-09-06 10:21 UTC
Hi, 

I notice when trying to convert from "Add directory" method. for example the folder name is "Chapter 11" -> it will be output a new MOBI file but in the format of "Chapter 11..mobi"  Having extra ".." in the end 

The KCC is obviously can't find the generated .mobi and it just hangs when trying to publish MOBI file 

You can transfer and have Kindle read the Chapter 11..mobi though

**Comment by AcidWeb** [comment] 2019-09-06 20:14
I can't replicate this issue.

**Comment by aleifuu** [comment] 2019-09-10 02:28
`Preparing source images...
Checking images...
Processing images...
Creating EPUB file...
Traceback (most recent call last):
  File "/usr/lib/python3.5/shutil.py", line 538, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/var/host/media/removable/SD Card/dbz/Chapter 11.mobi' -> '/var/host/media/removable/SD Card/dbz/Chapter 11.mobi_toclean'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/kindlecomicconverter/KCC_gui.py", line 383, in run
    item, comic2ebook.options.covers[outputPath.index(item)][1]))
  File "/home/pi/.local/lib/python3.5/site-packages/kindlecomicconverter/comic2ebook.py", line 1166, in makeMOBIFix
    move(mobiPath, mobiPath + '_toclean')
  File "/usr/lib/python3.5/shutil.py", line 552, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.5/shutil.py", line 251, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.5/shutil.py", line 114, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/var/host/media/removable/SD Card/dbz/Chapter 11.mobi'


^C
`

**Comment by AcidWeb** [comment] 2019-09-11 14:22
I will try to find the cause.

**Comment by luiznux** [comment] 2019-10-14 06:16
I'm having the same problem...

**Comment by AcidWeb** [comment] 2019-10-21 11:25
I can't replicate this issue but I will be fixed in 6.0.

**Closed by AcidWeb** 2019-10-21 11:25 UTC
Labels: Bug, Linux
