### ISSUE TITLE
[Feature Request] Add option for the insertion of a single blank page to correct alignment of two-page spreads

### ISSUE THREAD

**Issue by senecaFallsConvention** [ciromattia/kcc#640] opened 2023-12-10 00:34 UTC
I don't know if it's something inherent to Kobo devices or to the conversion process, but the first page of any file created with KCC, at least when viewed on a Kobo Libra 2, takes up two pages. This is problematic when the images in the archive were already arranged so that two-page spreads would properly fall on two pages. This causes the images to fall out of alignment and all two-page spreads to be split between one page and the next. It's possible to remedy this by extracting the archive and duplicating two pages near the beginning so the alignment is fixed, but that takes significantly more time (especially when converting numerous archives) than **a checkbox option that would insert a single blank page and fix the alignment during the conversion process,** no extraction necessary.

If, as I think, this is a quirk of Kobo devices, an option such as this could save many people a lot of time.

**Comment by axu2** [comment] 2023-12-10 01:22
- Duplicate #433 
- Duplicate #557 
- potential fix #561 

Are you able to run pull request code? https://github.com/ciromattia/kcc/wiki/Installation#install-from-source

**Comment by senecaFallsConvention** [comment] 2023-12-10 16:00
> * Duplicate [Empty cover page #433](https://github.com/ciromattia/kcc/issues/433)
> 
>     * Duplicate [First page duplicated  #557](https://github.com/ciromattia/kcc/issues/557)
> 
>     * potential fix [New arguments to CLI #561](https://github.com/ciromattia/kcc/pull/561)
> 
> 
> Are you able to run pull request code? https://github.com/ciromattia/kcc/wiki/Installation#install-from-source
> 
> This would have to be an option, on Kindles the duplicated page is necessary for double page spread alignment.

I run the flatpak GUI version of KCC and I'd rather not swap to using a source-compiled CLI version. 

I understand that this would need to be an option, which I specified in the original request. As an option, it could only benefit the people who need it and inconvenience no one.

**Comment by VampiroMedicado** [comment] 2024-01-02 05:52
Hi @senecaFallsConvention, could you provide a picture to illustrate the issue?

I suspect that the cover page, which is displayed during book selection, and the first page of the book are identical. On your `Kobo Libra 2`, it seems both pages are shown simultaneously.

My preferred choice for a workaround to this issue would be to skip the first page. Removing the cover file could hinder your ability to search and easily distinguish between different books. Additionally, adding a blank page would not add any meaningful value. 🤔

**Comment by VampiroMedicado** [comment] 2024-01-03 02:04
Hi @senecaFallsConvention I've created a branch with a quick and dirty fix.

Check if it works for your use case.

Branch: https://github.com/VampiroMedicado/kcc/tree/skip-first-page

https://github.com/ciromattia/kcc/wiki/Installation#install-from-source

**Comment by axu2** [comment] 2024-01-04 05:09
I just tried your branch on my Kindle.
Previously, my files would be aligned when reading in landscape. (rotate and split option)
With your branch, alignment is lost.

I imagine it works fine for the Kobo case though.

**Comment by peiskios** [comment] 2024-01-07 20:20
> I don't know if it's something inherent to Kobo devices or to the conversion process, but the first page of any file created with KCC, at least when viewed on a Kobo Libra 2, takes up two pages. This is problematic when the images in the archive were already arranged so that two-page spreads would properly fall on two pages. This causes the images to fall out of alignment and all two-page spreads to be split between one page and the next. It's possible to remedy this by extracting the archive and duplicating two pages near the beginning so the alignment is fixed, but that takes significantly more time (especially when converting numerous archives) than **a checkbox option that would insert a single blank page and fix the alignment during the conversion process,** no extraction necessary.
> 
> If, as I think, this is a quirk of Kobo devices, an option such as this could save many people a lot of time.

I'm having the same issue where the wrong pages are being matched up but I don't understand how you fixed it. how do I extract the archive? is this something I can fix with calibre? I'm really new to all this

**Comment by axu2** [comment] 2024-01-07 21:12
Right click the cbz in windows, 7zip, extract. Then duplicate the cover page. Then drag the whole folder into kcc. @peiskios

**Comment by VampiroMedicado** [comment] 2024-01-07 22:16
@peiskios if you have time try my fix for EPUBs specifically.

https://github.com/ciromattia/kcc/issues/640#issuecomment-1874767086

**Comment by peiskios** [comment] 2024-01-08 04:48
im not sure if I did it right, but the fix that removes page 0000 didn't work for me. 

extracting the contents of the cbz file into a folder and duplicating the cover page worked! Is there a way to make it a blank page instead? Would I just make a "blank" jpeg of the same dimensions/resolution as one of the pages and name it the same as the cover page copy? Not a huge deal if I'm stuck with two cover pages at the beginning, but I thought I'd ask in case it is possible

**Comment by axu2** [comment] 2024-01-08 04:51
@peiskios In what way did it not work? Make sure you are on the correct branch in GitHub Desktop.

**Comment by peiskios** [comment] 2024-01-08 04:53
> @peiskios In what way did it not work? Make sure you are on the correct branch in GitHub Desktop.
> 
> And yes, you could just use a blank page with the same name.

it just didn't do anything and looked the same. duplicating the first page is simpler for me so ill just stick with that until there's an easier/faster fix. thanks for your help!

**Comment by axu2** [comment] 2024-01-08 05:09
@peiskios Can you confirm on GitHub Desktop you are on the right branch? `skip-first-page`

![image](https://github.com/ciromattia/kcc/assets/20757319/e50a4211-67e5-4ed4-8c56-e2bf0505acaa)

**Comment by VampiroMedicado** [comment] 2024-01-10 17:49
> I would also love for this to become a feature inside the KCC GUI, doing it by hand is very tedious. However, while adding or removing a page would indeed fix the problem for a book, it wouldn't fix it for multiple files combined into a single epub. For example, if you own multiple chapters of a single volume and want to combine them into one, if some chapters have an odd number of pages, it would throw off the order again due to Kobo ignoring any indicators that one page should be displayed alone.
> 
> This is not an issue on Kindle devices as far as I've tested.

If you have a Kobo, could you try the branch on the following comment; https://github.com/ciromattia/kcc/issues/640#issuecomment-1874767086

Could you provide us an example? Check also the following comment: https://github.com/ciromattia/kcc/issues/640#issuecomment-1873642771 if it explains the issue.

**Comment by PrinceSeven** [comment] 2024-01-10 19:37
> If you have a Kobo, could you try the branch on the following comment; [#640 (comment)](https://github.com/ciromattia/kcc/issues/640#issuecomment-1874767086)
> 
> Could you provide us an example? Check also the following comment: [#640 (comment)](https://github.com/ciromattia/kcc/issues/640#issuecomment-1873642771) if it explains the issue.
> 
> I have two kindles, but not a Kobo to check this 😅

If you were to quickly build it into the GUI I'd test it out, as I'm really terrible at using from source and other similar applications.

As for the second thing I was talking about, I don't think it's really relevant in the end, simply that combining chapters into a single epub can wield to unsatisfying results.

**Comment by VampiroMedicado** [comment] 2024-01-10 19:45
> > If you have a Kobo, could you try the branch on the following comment; [#640 (comment)](https://github.com/ciromattia/kcc/issues/640#issuecomment-1874767086)
> > Could you provide us an example? Check also the following comment: [#640 (comment)](https://github.com/ciromattia/kcc/issues/640#issuecomment-1873642771) if it explains the issue.
> > I have two kindles, but not a Kobo to check this 😅
> 
> If you were to quickly build it into the GUI I'd test it out, as I'm really terrible at using from source and other similar applications.
> 
> As for the second thing I was talking about, I don't think it's really relevant in the end, simply that combining chapters into a single epub can wield to unsatisfying results.

It's always on there's no checkbox at the moment, just a quick fix to try it.

I guess you meant an executable: https://www.mediafire.com/file/w170ymzcnvogkr0/KCC_5.6.5.exe/file.

Just run it and try to make an epub.

![imagen](https://github.com/ciromattia/kcc/assets/149981282/52f343c3-0c7e-4e19-9dea-5937b28fab45)

On the left the first page which is used as a cover and on the right the first page on the EPUB (page 2).

**Comment by PrinceSeven** [comment] 2024-01-10 19:50
The download link doesn't work, Mediafire deems it as a dangerous file, might want to zip it first to counter this

**Comment by VampiroMedicado** [comment] 2024-01-10 19:53
> The download link doesn't work, Mediafire deems it as a dangerous file, might want to zip it first to counter this

Good idea, https://www.mediafire.com/file/dv6e16t0rbhokvn/KCC_5.6.5.exe.zip/file.

**Comment by axu2** [comment] 2024-01-10 20:12
Please remove your media fire links and instead use GitHub Actions on your fork to generate exe. @VampiroMedicado

**Comment by VampiroMedicado** [comment] 2024-01-10 20:13
> Please remove your media fire links and instead use GitHub Actions on your fork to generate exe. @VampiroMedicado 

Ok, will do.

**Comment by PrinceSeven** [comment] 2024-01-10 20:20
I've tested it : https://imgur.com/a/ktoGvDd
Can confirm it works, although the result is that upon opening the book, the first page displayed alone is not the cover but page 001 instead, whichI think is a shame because the only ways to see the full cover art ends up being to put the Kobo in sleep mode, where it will display the cover art of what you are currently reading as a lock screen.

Still, this is a big improvement as it does work (as can be seen on the third image in my imgur link which is a double spread), thank you.

**Comment by axu2** [comment] 2024-01-10 20:26
@PrinceSeven Does Kobo store manga start on the cover instead of page 1?

**Comment by PrinceSeven** [comment] 2024-01-10 20:31
cover.jpg will display as the lock screen and cover art when browsing, but Page 1 (so the first page shown individually from the others) will be the first image in the epub (aside from the cover), so in this case 001.jpg (000.jpg which KCC deleted was a duplicate of the cover art).

**Comment by PrinceSeven** [comment] 2024-01-10 20:42
My ideal solution personally would be to add a blank image as the second image in the Epub. That way the cover art cover art would remain the first pic you see when you open the ebook, while still reordering properly the pages.

**Comment by VampiroMedicado** [comment] 2024-01-10 21:05
> cover.jpg will display as the lock screen and cover art when browsing, but Page 1 (so the first page shown individually from the others) will be the first image in the epub (aside from the cover), so in this case 001.jpg (000.jpg which KCC deleted was a duplicate of the cover art).

I see, if you want to view the cover art, that might be an issue. As @axu2 mentioned, on Kindle, we can go back and check the cover art, but it always starts from the first page.

Personally, I don't care a lot about the cover art besides knowing what I'm reading when it's locked, but we could provide both options for people who do care.

1. Add a 1x1 blank PNG as page 0001.
2. Remove page 0000 after cover.jpg is created.

What do you think, @axu2?

I'll check if EPUB has any features to work like the Kindle does and get back to you. Thanks @PrinceSeven for the help!

**Comment by axu2** [comment] 2024-01-10 21:10
@PrinceSeven how does **Kobo Store** manga behave?

**Comment by VampiroMedicado** [comment] 2024-01-10 21:40
I'll let this comment to add more information.

https://github.com/kobolabs/epub-spec#cover-images

> Covers should also be listed in the OPF metadata section. The metadata indicates the cover by pointing to the ID of the cover file in the manifest. Kobo uses this tag to identify which image to display as a thumbnail within user's libraries across platforms.
>
>Ex. OPF metadata:
>
> `<meta name="cover" content="cover-image"/>`
> 
> Manifest item listing:
> 
> `<item href="cover.jpg" id="cover-image" media-type="image/jpeg"/>`
> 
> **Cover images must be contained in their own XHTML files.**

**content.opf**

KCC

```
...
<meta name="cover" content="cover"/>
...
<item id="cover" href="Images/cover.jpg" media-type="image/jpeg" properties="cover-image"/>
...
```

I see a different content attribute that might or might not affect the behavior, and we do not have a cover.xhtml file. If we get our hands on a Kobo Store epub file we might be able to confirm this.

**Closed** 2024-05-17 16:56 UTC
Labels: Enhancement, GUI, good first issue
